[[plugins_list]]
== List of plugins

This is a non-exhaustive list of Erlang.mk plugins, sorted
alphabetically.

=== efene.mk

An https://github.com/ninenines/efene.mk[Efene plugin] for Erlang.mk.
http://efene.org/[Efene] is an alternative language for the BEAM.

=== elixir.mk

An https://github.com/botsunit/elixir.mk[Elixir plugin] for
Erlang.mk. http://elixir-lang.org/[Elixir] is an alternative
language for the BEAM.

=== elvis.mk

An https://github.com/inaka/elvis.mk[Elvis plugin] for Erlang.mk.
Elvis is an https://github.com/inaka/elvis[Erlang style reviewer].

=== geas

https://github.com/crownedgrouse/geas[Geas] gives aggregated
information on a project and its dependencies, and is available
as an Erlang.mk plugin.

=== hexer.mk

An https://github.com/inaka/hexer.mk[Hex plugin] for Erlang.mk
using the `hexer` tool.

=== hexpm.mk

Another https://github.com/botsunit/hexpm.mk[Hex plugin] for
Erlang.mk, with support for Hex dependency operators.

=== jorel

https://github.com/emedia-project/jorel[Jorel] is Just anOther RELease 
assembler for Erlang/OTP, and is available as an Erlang.mk plugin.

=== lfe.mk

An https://github.com/ninenines/lfe.mk[LFE plugin] for Erlang.mk.
LFE, or http://lfe.io/[Lisp Flavoured Erlang], is an alternative
language for the BEAM.

=== mix.mk

A https://github.com/botsunit/mix.mk[Mix plugin] for Erlang.mk,
to generate a compatible configuration file for
http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html[Mix].

=== reload.mk

A https://github.com/bullno1/reload.mk[live reload plugin] for Erlang.mk.

=== rust.mk

A https://github.com/goertzenator/rust.mk[plugin] to build https://www.rust-lang.org/[Rust] crates and install binaries into `priv/`.  

